app/design/frontend/base/default/layout/rakuten/rakutenpay.xml, app/design/frontend/base/default/template/rakuten/rakutenpay/direct/success.phtml
**Jira Card:** [[Pay] incluir link do boleto na página de sucesso do próprio magento.](https://rakutenbrazil.atlassian.net/browse/CON-91)
=> [Pay] incluir link do boleto na página de sucesso do próprio magento.

lib/RakutenpayPhpSdk/source/Resources/Http.php
**Jira Card:** [[Pay] Remover JSON_PRESERVE_ZERO_FRACTION](https://rakutenbrazil.atlassian.net/browse/CON-102)
=> [Pay] Remover JSON_PRESERVE_ZERO_FRACTION

lib/RakutenpayPhpSdk/source/Library.php
**Jira Card:** [[Pay][Magento1] Adicionar Condição na Constant Global do PHP](https://rakutenbrazil.atlassian.net/browse/CON-102)
=> [Pay][Magento1] Adicionar Condição na Constant Global do PHP

app/code/community/Rakuten/RakutenPay/Helper/Data.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/creditcard.phtml, lib/RakutenpayPhpSdk/source/Helpers/EnvironmentInformation.php, lib/RakutenpayPhpSdk/source/Helpers/JsonFormat.php, lib/RakutenpayPhpSdk/source/Library.php, lib/RakutenpayPhpSdk/source/Resources/Http.php, lib/RakutenpayPhpSdk/source/Resources/Log/Environment.php
**Jira Card:** [[Pay] Remover JSON_PRESERVE_ZERO_FRACTION](https://rakutenbrazil.atlassian.net/browse/CON-102)
=> Refatorado para PHP 5.5 e Magento 1.7.0.2

app/code/community/Rakuten/RakutenPay/Model/InstallmentsMethod.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/creditcard.phtml, lib/Rakuten/Connector/src/Services/Transactions/Checkout.php, skin/frontend/base/default/rakuten/rakutenpay/js/credit-card.js, skin/frontend/base/default/rakuten/rakutenpay/js/direct-payment.js
**Jira Card:** [[Pay][Magento] Não está exibindo as parcelas na opção de pagamento de Cartão de Crédito](https://rakutenbrazil.atlassian.net/browse/CON-130)
=> [Pay][Magento] Não está exibindo as parcelas na opção de pagamento de Cartão de Crédito

app/code/community/Rakuten/RakutenPay/Model/OrderAddress.php, lib/Rakuten/Connector/src/Enum/Address.php, lib/Rakuten/Connector/src/Helpers/StringFormat.php, lib/Rakuten/Connector/src/Parsers/Customer.php
**Jira Card:** [[Pay][Magento] Erro Na Geração de Boletos no Bradesco](https://rakutenbrazil.atlassian.net/browse/CON-136)
=> [Pay][Magento] Erro Na Geração de Boletos no Bradesco

lib/Rakuten/Connector/src/Helpers/JsonFormat.php
**Jira Card:** [[Pay][Connector] JSON Quebrando no installment_amount e total](https://rakutenbrazil.atlassian.net/browse/CON-137)
=> [Pay][Connector] JSON Quebrando no installment_amount e total

app/code/community/Rakuten/RakutenPay/Model/PaymentMethod.php, lib/Rakuten/Connector/src/Domains/Requests/DirectPayment/Boleto/Request.php, lib/Rakuten/Connector/src/Domains/Requests/DirectPayment/CreditCard/Request.php, lib/Rakuten/Connector/src/Domains/Requests/Discount.php, lib/Rakuten/Connector/src/Parsers/Order.php
**Jira Card:** [[Pay][Connector] Plugin não realiza descontos gerados no Magento](https://rakutenbrazil.atlassian.net/browse/CON-156)
=> [Pay][Connector] Plugin não realiza descontos gerados no Magento

app/code/community/Rakuten/RakutenPay/Model/InstallmentsMethod.php
**Jira Card:** [[Pay][Connector] Não está exibindos as Parcelas no Checkout](https://rakutenbrazil.atlassian.net/browse/CON-161)
=> [Pay][Connector] Não está exibindos as Parcelas no Checkout

app/code/community/Rakuten/RakutenPay/Block/Form/Boleto.php, app/code/community/Rakuten/RakutenPay/Block/Form/CreditCard.php, app/code/community/Rakuten/RakutenPay/Model/PaymentMethod.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/design/frontend/base/default/layout/rakuten/rakutenpay.xml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/boleto.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/creditcard.phtml, skin/frontend/base/default/rakuten/rakutenpay/css/direct-payment-onestepcheckout.css, skin/frontend/base/default/rakuten/rakutenpay/js/boleto.js, skin/frontend/base/default/rakuten/rakutenpay/js/credit-card.js, skin/frontend/base/default/rakuten/rakutenpay/js/rakutenpay-onestepcheckout-before-save.js
**Ticket Jira:** [[Pay][Connector] Ajustar o Plugin para ser compatível com o OneStepCheckout](https://rakutenbrazil.atlassian.net/browse/CON-160)
Funcionalidade a ser corrigida: Integrar o Plugin do RakutenPay com o OneStepCheckout.
=> [Pay][Connector] Ajustar o Plugin para ser compatível com o OneStepCheckout

app/code/community/Rakuten/RakutenPay/Block/Form/Boleto.php, app/code/community/Rakuten/RakutenPay/Block/Form/CreditCard.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/boleto.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/creditcard.phtml, skin/frontend/base/default/rakuten/rakutenpay/js/rakutenpay-onestepcheckout-before-save.js
**Ticket Jira:** [[Pay][Connector] Plugin não está considerando a Forma de envio no OSC](https://rakutenbrazil.atlassian.net/browse/CON-170)
Funcionalidade a ser corrigida: Erro ao mudar o envio no OSC, após os dados de pagamento estarem concluídos.
=> [Pay][Connector] Plugin não está considerando a Forma de envio no OSC

app/code/community/Rakuten/RakutenPay/Helper/Data.php, app/code/community/Rakuten/RakutenPay/Helper/Log.php, app/code/community/Rakuten/RakutenPay/Model/NotificationMethod.php, app/code/community/Rakuten/RakutenPay/etc/config.xml
**Jira Card:** [[Pay][Connector] Erro na notificação do Webhook](https://rakutenbrazil.atlassian.net/browse/CON-185)
Este PR ajusta o Webhook que está acusando erro no Reference.
=> [Pay][Connector] Erro na notificação do Webhook

README.md
Atualização para o Readme.md e implementação da Wiki para o Rakuten Connector
=> [Pay][Connector] Refinamento-Readme_

app/code/community/Rakuten/RakutenPay/controllers/PaymentController.php
**Jira Card:** [[Pay][Connector] Ajustar o Sales Order Detail para exibir o Total sem a taxa de juros comprador](https://rakutenbrazil.atlassian.net/browse/CON-207)
Este PR Ajusta a exibição do Sales Order Detail removendo a taxa de juros comprador.
=> [Pay][Connector] Ajustar o Sales Order Detail para exibir o Total sem a taxa de juros comprador

app/code/community/Rakuten/RakutenPay/Block/Info/Boleto.php, app/code/community/Rakuten/RakutenPay/Helper/Data.php, app/code/community/Rakuten/RakutenPay/Helper/Log.php, app/code/community/Rakuten/RakutenPay/Helper/Refund.php, app/code/community/Rakuten/RakutenPay/Model/Cron/OrderState.php, app/code/community/Rakuten/RakutenPay/Model/NotificationMethod.php, app/code/community/Rakuten/RakutenPay/Model/Observer.php, app/code/community/Rakuten/RakutenPay/controllers/BilletController.php, app/code/community/Rakuten/RakutenPay/controllers/PaymentController.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/design/adminhtml/default/default/template/rakuten/rakutenpay/info/boleto.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/direct/success.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/info/boleto.phtml, lib/Rakuten/Connector/src/Enum/DirectPayment/State.php, lib/Rakuten/Connector/src/Resources/Http/RakutenPay/Validator/ResponseValidate.php
**Jira Card:** [[Pay][Connector] Salvar a Transição de Status no State do Magento](https://rakutenbrazil.atlassian.net/browse/CON-209)
Este PR Cria os transicionamentos para o Estado e Status do Magento.
Ajustado a Cron.
=> [Pay][Connector] Salvar a Transição de Status no State do Magento

app/code/community/Rakuten/RakutenPay/Block/Info/Boleto.php, app/code/community/Rakuten/RakutenPay/Block/Info/CreditCard.php, app/code/community/Rakuten/RakutenPay/Helper/Data.php, app/code/community/Rakuten/RakutenPay/Model/NotificationMethod.php, app/code/community/Rakuten/RakutenPay/controllers/Adminhtml/LogController.php, app/code/community/Rakuten/RakutenPay/controllers/PaymentController.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/design/adminhtml/default/default/template/rakuten/rakutenpay/info/boleto.phtml, app/design/adminhtml/default/default/template/rakuten/rakutenpay/info/credit_card.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/direct/success.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/boleto.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/creditcard.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/info/boleto.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/info/credit_card.phtml, lib/Rakuten/Connector/src/Parsers/Transaction/CreditCard/Response.php, lib/Rakuten/Connector/src/Resources/Log/Logger.php, skin/frontend/base/default/rakuten/rakutenpay/js/rakutenpay-onestepcheckout-before-save.js
**Jira Card:** [[Pay][Connector] Triggar o Status Cancelado quando o resultado por Declined e Ajustar visualizações no Dashboard](https://rakutenbrazil.atlassian.net/browse/CON-215)
Este PR corrige o Status Declined e adiciona novas funcionalidades.
=> [Pay][Connector] Triggar o Status Cancelado quando o resultado por Declined e Ajustar visualizações no Dashboard

app/code/community/Rakuten/RakutenPay/Model/PaymentMethod.php, app/code/community/Rakuten/RakutenPay/controllers/NotificationController.php, lib/Rakuten/Connector/src/Domains/Requests/DirectPayment/Boleto.php, lib/Rakuten/Connector/src/Domains/Requests/DirectPayment/Boleto/Request.php, lib/Rakuten/Connector/src/Domains/Requests/DirectPayment/CreditCard.php, lib/Rakuten/Connector/src/Domains/Requests/DirectPayment/CreditCard/Request.php, lib/Rakuten/Connector/src/Domains/Requests/Discount.php, lib/Rakuten/Connector/src/Domains/Requests/Tax.php, lib/Rakuten/Connector/src/Library.php, lib/Rakuten/Connector/src/Parsers/Order.php, lib/Rakuten/Connector/src/Resources/Builder/Pooling/OrderStatus.php, lib/Rakuten/Connector/src/Resources/Connection/Base/Pooling/OrderStatus.php, lib/Rakuten/Connector/src/Resources/Http/RakutenPay/Http.php, lib/Rakuten/Connector/src/Services/Pooling/OrderStatus.php
**Jira Card:** [[Pay][Connector] Adicionar Taxas/Impostos quando finalizar o pedido](https://rakutenbrazil.atlassian.net/browse/CON-219)
Este PR Adiciona o Tax Amount da Order do Magento no Plugin.
=> [Pay][Connector] Adicionar Taxas/Impostos quando finalizar o pedido

skin/frontend/base/default/rakuten/rakutenpay/js/rakutenpay-onestepcheckout-before-save.js
**Jira Card:** [[Pay][Connector] Não atualiza do Token quando é inserido um novo Cartão no OSC](https://rakutenbrazil.atlassian.net/browse/CON-220)
Este PR Corrige a atualização do Token.
=> [Pay][Connector] Não atualiza do Token quando é inserido um novo Cartão no OSC

app/code/community/Rakuten/RakutenPay/Helper/Data.php, app/code/community/Rakuten/RakutenPay/etc/config.xml
**Jira Card:** [[Pay] Gerar a Fatura após o Pedido ir para Processing](https://rakutenbrazil.atlassian.net/browse/CON-237)
Este PR Gera uma Fatura quando transicionar para Processing.
=> [Pay] Gerar a Fatura após o Pedido ir para Processing

app/code/community/Rakuten/RakutenPay/etc/config.xml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/boleto.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/form/creditcard.phtml, skin/frontend/base/default/rakuten/rakutenpay/js/credit-card.js, skin/frontend/base/default/rakuten/rakutenpay/js/rakutenpay-onestepcheckout-before-save.js
**Jira Card:** [[Pay] Refatorar o JS para o OSC](https://rakutenbrazil.atlassian.net/browse/CON-249)
Este PR Refatora o JS para ser usado no OSC.
=> [Pay] Refatorar o JS para o OSC

app/code/community/Rakuten/RakutenPay/controllers/PaymentController.php, app/design/frontend/base/default/template/rakuten/rakutenpay/form/creditcard.phtml, skin/frontend/base/default/rakuten/rakutenpay/js/boleto.js, skin/frontend/base/default/rakuten/rakutenpay/js/credit-card.js
**Jira Card:** [[Pay] Corrigir a geração de Fingerprint e Token no OnePage Checkout](https://rakutenbrazil.atlassian.net/browse/CON-270)
Este PR Corrige a geração de Token e Fingerprint no OnePage Checkout.
=> [Pay] Corrigir a geração de Fingerprint e Token no OnePage Checkout

app/code/community/Rakuten/RakutenPay/Model/InstallmentsMethod.php, app/code/community/Rakuten/RakutenPay/etc/config.xml
**Jira Card:** [[PAY] Ajustar o parcelamento na opção crédito](https://rakutenbrazil.atlassian.net/browse/CON-316)
Este PR Corrige a flag das Parcelas.
=> [PAY] Ajustar o parcelamento na opção crédito

lib/Rakuten/Connector/src/Parsers/Order.php
**Jira Card:** [[Pay] Ajuste da categoria como string no payload](https://rakutenbrazil.atlassian.net/browse/CON-372)
Este PR Ajusta a categoria como string no payload.
=> [Pay] Ajuste da categoria como string no payload

lib/Rakuten/Connector/src/Parsers/Order.php
**Jira Card:** [[Pay] Refatorar categorias e nomes no payload](https://rakutenbrazil.atlassian.net/browse/CON-386)
Este PR Ajusta a a condição se não houver o campo 'name' nas categorias relacionadas ao produto.
=> [Pay] Refatorar categorias e nomes no payload

app/code/community/Rakuten/RakutenPay/etc/config.xml, skin/frontend/base/default/rakuten/rakutenpay/js/credit-card.js
**Jira Card:** [[Pay]  Adicionado ç/Ç na validação do HolderName](https://rakutenbrazil.atlassian.net/browse/CON-396)
Este PR Ajusta a validação do HolderName no credita-card.js
=> [Pay]  Adicionado ç/Ç na validação do HolderName

app/design/frontend/base/default/template/rakuten/rakutenpay/direct/success.phtml
**Jira Card:** [[Pay] Alterar modo de visualização do boleto para Modal](https://rakutenbrazil.atlassian.net/browse/CON-401)
Este PR altera o modo de exibição do boleto.
=> [Pay] Alterar modo de visualização do boleto para Modal

app/code/community/Rakuten/RakutenPay/Model/PaymentMethod.php, app/code/community/Rakuten/RakutenPay/controllers/PaymentController.php, lib/Rakuten/Connector/src/Enum/DirectPayment/CodeError.php, lib/Rakuten/Connector/src/Parsers/DirectPayment/Boleto/Request.php, lib/Rakuten/Connector/src/Parsers/DirectPayment/CreditCard/Request.php, lib/Rakuten/Connector/src/Parsers/Transaction/Boleto/Response.php, lib/Rakuten/Connector/src/Parsers/Transaction/CreditCard/Response.php
**Jira Card:** [[Pay] Magento em alguns casos está enviando duas vezes o mesmo pedido para ser criado](https://rakutenbrazil.atlassian.net/browse/CON-421)
Este PR trata o envio duplicado do charge.
=> [Pay] Magento em alguns casos está enviando duas vezes o mesmo pedido para ser criado

app/code/community/Rakuten/RakutenPay/Model/PaymentMethod.php, app/code/community/Rakuten/RakutenPay/etc/config.xml
**Jira Card:** [[Pay] Magento não está realizando o Batch](https://rakutenbrazil.atlassian.net/browse/CON-434)
Este PR Ajusta o Calculation Code.
=> [Pay] Magento não está realizando o Batch

app/code/community/Rakuten/RakutenPay/Block/Adminhtml/ValidateCredential.php, app/code/community/Rakuten/RakutenPay/controllers/Adminhtml/ValidateCredentialController.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/code/community/Rakuten/RakutenPay/etc/system.xml, app/design/adminhtml/default/default/template/rakuten/rakutenpay/system/config/validate-credential.phtml, lib/Rakuten/Connector/src/Parsers/Transaction/Authorization/Request.php, lib/Rakuten/Connector/src/Parsers/Transaction/Authorization/Response.php, lib/Rakuten/Connector/src/Resources/Http/RakutenPay/Authorization.php, lib/Rakuten/Connector/src/Services/Transactions/Authorization.php
**Jira Card:** [[Magento1] Validação de credenciais ](https://rakutenbrazil.atlassian.net/browse/CON-441)
Este PR Adiciona botão para Verificar Credenciais
=> [Magento1] Validação de credenciais

app/code/community/Rakuten/RakutenPay/controllers/PaymentController.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/design/frontend/base/default/layout/rakuten/rakutenpay.xml, app/design/frontend/base/default/template/rakuten/rakutenpay/info/boleto.phtml
**Jira Card:** [[Magento1] Adaptar rota de finalização de pedido para onepage do Magento](https://rakutenbrazil.atlassian.net/browse/CON-506)
Este PR Altera a rota de success.
=> [Magento1] Adaptar rota de finalização de pedido para onepage do Magento

app/code/community/Rakuten/RakutenPay/Model/InstallmentsMethod.php, skin/frontend/base/default/rakuten/rakutenpay/js/credit-card.js
**Jira Card:** [[Pay] Ajuste para Dot cosméticos](https://rakutenbrazil.atlassian.net/browse/PAY-531)
**Jira Card:** [[Pay] Ajuste juros comprador parcelas sem juros](https://rakutenbrazil.atlassian.net/browse/PAY-532)
Este PR Ajusta o arredondamento das parcelas sem juros do juros comprador e a ordem de execução do place order após a execução do createToken.
=> [Pay] Ajuste juros comprador e token de cartão de crédito

app/code/community/Rakuten/RakutenPay/Model/PaymentMethod.php, lib/Rakuten/Connector/src/Helpers/Document.php, skin/frontend/base/default/rakuten/rakutenpay/js/credit-card.js, skin/frontend/base/default/rakuten/rakutenpay/js/rakutenpay-before-save.js
**Jira Card:** [[Magento1] Ajustar o JS para resolver o conflito com outros plugins](https://rakutenbrazil.atlassian.net/browse/CON-559)
Este PR Corrige o conflito com outros plugins de pagamentos.
=> [Magento1] Ajustar o JS para resolver o conflito com outros plugins

app/code/community/Rakuten/RakutenPay/Block/Info/Boleto.php, app/code/community/Rakuten/RakutenPay/Model/BoletoDisplay.php, app/code/community/Rakuten/RakutenPay/controllers/PaymentController.php, app/code/community/Rakuten/RakutenPay/etc/config.xml, app/code/community/Rakuten/RakutenPay/etc/system.xml, app/design/adminhtml/default/default/template/rakuten/rakutenpay/info/credit_card.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/direct/success.phtml, app/design/frontend/base/default/template/rakuten/rakutenpay/info/boleto.phtml
**Jira Card:** [[Magento1] Criar configuração para opções de exibição do Boleto](https://rakutenbrazil.atlassian.net/browse/PAY-570)
Este PR Adiciona uma nova configuração de Boleto
=> [Magento1] Criar configuração para opções de exibição do Boleto
